import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
import Slide from "../components/home/Slide";
import Logo from "../components/home/Logo";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Logo></Logo>
      <Slide></Slide>
    </div>
  );
};

export default Home;
